# Basic config
baseURL = "https://mohit-k-s.github.io"
theme = "hugo-bearcub"
copyright = "Mohit Kumar"
defaultContentLanguage = "en"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# Setup syntax highlighting without inline styles.
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    noClasses = false
    style = "friendly"
    tabWidth = 4

# Navigation menus
[[menus.main]]
  name = "~"
  title = "Home"
  url = "/"
  weight = 1

[[menus.main]]
  name = "writings"
  url = "/blog/"
  weight = 2

# Language config
[languages]
  [languages.en]
    title = "Mohit's Page"
    languageName = "en-US"
    LanguageCode = "en-US"
    contentDir = "content"

[params]
  description = "Mohit's Page — a backend engineer writing about tech, systems, and life"
  favicon = "images/favicon.svg"
  images = ["images/share.webp"]
  title = "Mohit's Page"
  dateFormat = "2006-01-02"
  hideUntranslated = false
  themeStyle = "original"
  generateSocialCard = true

  [params.social]
    twitter = "shkcvd"

  [params.author]
    name = "Mohit Kumar"

[caches]
  [caches.images]
    dir = ':cacheDir/images'